<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGNKRJDm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGNKRJDm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGNKRJDm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGNKRJDm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGNKRJDm\App_KernelDevDebugContainer([
    'container.build_hash' => 'GNKRJDm',
    'container.build_id' => '2df6f797',
    'container.build_time' => 1646664066,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGNKRJDm');
