<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9bIdEcS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9bIdEcS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9bIdEcS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9bIdEcS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9bIdEcS\App_KernelDevDebugContainer([
    'container.build_hash' => '9bIdEcS',
    'container.build_id' => '770bc9ce',
    'container.build_time' => 1646647796,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9bIdEcS');
